In [2]:
import pandas as pd

In [6]:
bank_ds = pd.read_csv('loan.csv')

C:\Users\pabar\AppData\Local\Temp\ipykernel_1748\3558088723.py:1: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  bank_ds = pd.read_csv('loan.csv')

In [7]:
bank_ds.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
bank_ds.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [14]:
selected_cols = [
    "loan_amnt",
    "term",
    "int_rate",
    "installment",
    "grade",
    "sub_grade",
    "emp_length",
    "home_ownership",
    "annual_inc",
    "verification_status",
    "purpose",
    "dti",
    "delinq_2yrs",
    "inq_last_6mths",
    "open_acc",
    "pub_rec",
    "revol_util",
    "total_acc",
    "loan_status"
]

In [16]:
bank_ds = bank_ds[selected_cols]
bank_ds.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_util,total_acc,loan_status
0,2500,36 months,13.56,84.92,C,C1,10+ years,RENT,55000.0,Not Verified,debt_consolidation,18.24,0.0,1.0,9.0,1.0,10.3,34.0,Current
1,30000,60 months,18.94,777.23,D,D2,10+ years,MORTGAGE,90000.0,Source Verified,debt_consolidation,26.52,0.0,0.0,13.0,1.0,24.2,44.0,Current
2,5000,36 months,17.97,180.69,D,D1,6 years,MORTGAGE,59280.0,Source Verified,debt_consolidation,10.51,0.0,0.0,8.0,0.0,19.1,13.0,Current
3,4000,36 months,18.94,146.51,D,D2,10+ years,MORTGAGE,92000.0,Source Verified,debt_consolidation,16.74,0.0,0.0,10.0,0.0,78.1,13.0,Current
4,30000,60 months,16.14,731.78,C,C4,10+ years,MORTGAGE,57250.0,Not Verified,debt_consolidation,26.35,0.0,0.0,12.0,0.0,3.6,26.0,Current

In [20]:
bank_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Data columns (total 19 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            int64
 1   term                 object
 2   int_rate             float64
 3   installment          float64
 4   grade                object
 5   sub_grade            object
 6   emp_length           object
 7   home_ownership       object
 8   annual_inc           float64
 9   verification_status  object
 10  purpose              object
 11  dti                  float64
 12  delinq_2yrs          float64
 13  inq_last_6mths       float64
 14  open_acc             float64
 15  pub_rec              float64
 16  revol_util           float64
 17  total_acc            float64
 18  loan_status          object
dtypes: float64(10), int64(1), object(8)
memory usage: 327.7+ MB

In [41]:
bank_ds['loan_status'].value_counts()/len(bank_ds)*100  ##embalanced class, based on values in %

loan_status
Fully Paid                                             46.090448
Current                                                40.682444
Charged Off                                            11.574234
Late (31-120 days)                                      0.968608
In Grace Period                                         0.395989
Late (16-30 days)                                       0.165305
Does not meet the credit policy. Status:Fully Paid      0.087939
Does not meet the credit policy. Status:Charged Off     0.033663
Default                                                 0.001371
Name: count, dtype: float64

Considering completed loans to ensure a reliable target

In [45]:
bank_ds = bank_ds[bank_ds['loan_status'].isin(["Fully Paid","Charged Off"])]

In [47]:
len(bank_ds)

1303607

In [51]:

bank_ds['target'] = bank_ds['loan_status'].map({
    "Fully Paid": 0,
    "Charged Off":1
})

In [65]:
bank_ds['target'].value_counts(normalize=True)

target
0    0.799284
1    0.200716
Name: proportion, dtype: float64

In [ ]:
bank_ds.drop()

In [69]:
(bank_ds.isnull().sum() / len(bank_ds) * 100).sort_values(ascending=False)

emp_length             5.788094
revol_util             0.062135
dti                    0.023934
inq_last_6mths         0.000077
loan_amnt              0.000000
loan_status            0.000000
total_acc              0.000000
pub_rec                0.000000
open_acc               0.000000
delinq_2yrs            0.000000
purpose                0.000000
term                   0.000000
verification_status    0.000000
annual_inc             0.000000
home_ownership         0.000000
sub_grade              0.000000
grade                  0.000000
installment            0.000000
int_rate               0.000000
target                 0.000000
dtype: float64

In [81]:
bank_ds['emp_length'].describe()

count       1228153
unique           11
top       10+ years
freq         428547
Name: emp_length, dtype: object

In [75]:
banks_ds

NameError: name 'banks_ds' is not defined